### ISSUE TITLE
Add Navigation Component

### ISSUE THREAD

**Issue by rossanafmenezes** [rossanafmenezes/Kakelandet_My_Cookbook#9]
- [x] Add Navigation LIbrary #10 
- [x] Add fragments for each screen #10
- [x] Add menu and navigation to each of the fragments #10
